markdown: redcarpet
redcarpet:
  extensions: ["tables"]
exclude: ["*.Rmd"]
url: http://nicolewhite.github.io
source: /Users/nicole/Documents/GitHub/nicolewhite.github.io
destination: /Users/nicole/Desktop/_site
name: Nicole White
description: Graphs | Math | R | Python
