markdown: redcarpet
redcarpet:
  extensions: ["tables"]
url: http://nicolewhite.github.io
source: C:/Users/Nicole/Documents/GitHub/nicolewhite.github.io
destination: C:/Users/Nicole/Desktop/_site
name: Nicole White
description: Graphs | Math | R | Python
